repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: (migrations/|tests/|docs/|static/|media/).*

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: (migrations/|tests/|docs/|static/|media/).*

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff

  - repo:  https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: ["-c pyproject.toml"]
      additional_dependencies: ["toml"]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: ["--in-place", "--recursive", "--blank"]
